company_about: null;
company_account_name: "The United Trades (R)";
company_account_no: "04191210000313";
company_address: "010, A-2 BLOCK, 7TH MAIN, 8TH CROSS, 2ND BLOCK JAYNAGAR, BANGALORE 560011";
company_bank: "Canara Bank";
company_branch: "Girinagar branch, Bangalore";
company_cor_address: "#1141, 2nd Main, 1st Cross, Hoskerehalli, BSK 3rd Stage,\nBangalore 560085";
company_email: "info@theunitedtraders.co.in";
company_gst: "29AAXPA4078K2Z0";
company_ifsc_code: "CNRB 0010677";
company_image: "logo.png";
company_mobile: "9845400122";
company_mobile2: "8626728620";
company_name: "THE UNITED TRADERS (Regd.)";
company_old_address: "No. 205, 2nd Floor, MONEY CHAMBER, No. 6, K. H. Road, Bangalore - 560027";
company_pan: "AAXPA4078K";
company_short: "UT";
company_sign: "sign.png";
company_state: "KARNATAKA";
company_status: "Active";
company_to_email: "info@theunitedtraders.co.in";
created_at: null;
created_by: null;
id: 1;
updated_at: null;
updated_by: null;
