{
    "data": {
        "id": 10,
        "tax_invoice_date": "2025-11-11",
        "tax_invoice_no": "4",
        "tax_invoice_ref": "UT\/TX\/2025-26\/4",
        "tax_invoice_mill_id": 1,
        "mill_name": "BALAJI MALT (P) LTD",
        "tax_invoice_discount": "0",
        "tax_invoice_payment_terms": "dsfs",
        "tax_invoice_type": "COM",
        "tax_invoice_description": "sdff",
        "tax_invoice_cgst": "9",
        "tax_invoice_igst": "0",
        "tax_invoice_sgst": "9",
        "tax_invoice_hsn_code": "996111",
        "created_by": "superadmin",
        "created_at": "2025-11-11T13:23:45.000000Z",
        "updated_at": "2025-11-11T13:23:45.000000Z",
        "updated_by": null,
        "subs": [
            {
                "id": 47,
                "tax_invoice_sub_ref": "UT\/TX\/2025-26\/4",
                "tax_invoice_sub_billing_ref": "2025-26-323",
                "tax_invoice_sub_purchase_date": "2025-11-11",
                "tax_invoice_sub_tones": "23.00",
                "tax_invoice_sub_bf": "230\/LWC\/REEL",
                "tax_invoice_sub_sale_rate": "57.00",
                "tax_invoice_sub_purchase_rate": "55.00",
                "tax_invoice_sub_rate_diff": "2.00",
                "tax_invoice_sub_commn": "46",
                "tax_invoice_sub_mill_id": 1,
                "tax_invoice_sub_party_id": 1
            }
        ]
    },
    "mill": {
        "id": 1,
        "mill_short": "BALAJI MALT",
        "mill_name": "BALAJI MALT (P) LTD",
        "mill_billing_address": "PLOT  NO 8 KIADB INDUSTRIAL AREA\nSOMMANHALLI VILLAGE   MADDUR   TALUK\nMANDYA DIS- 571429",
        "mill_gstin": "29AACCB2151L1ZO",
        "mill_shipping_address": "Bangalore",
        "mill_state": "KARNATAKA",
        "mill_email": null,
        "mill_bank_ac_no": "4546068340",
        "mill_bank_name": "KOTAK MAHINDRA BANK LTD",
        "mill_bank_ifsc": "KKBK0008045",
        "mill_bank_branch_name": "SAHAKAR NAGAR BANGALORE",
        "mill_percentage": "0.00",
        "mill_cp_name": null,
        "mill_cp_mobile": null,
        "mill_cp_email": null,
        "mill_type": "Mill",
        "mill_status": "Active",
        "created_at": "2025-10-30T10:35:17.000000Z",
        "created_by": "superadmin",
        "updated_at": "2025-11-04T05:38:57.000000Z",
        "updated_by": "superadmin"
    }
}